-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.user_captcha_log_entries
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    token character varying COLLATE pg_catalog."default",
    is_success boolean,
    response json,
    user_id uuid,
    CONSTRAINT user_captcha_pkey PRIMARY KEY (id),
    CONSTRAINT user_captcha_log_entries_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_captcha_log_entries
    OWNER to postgres;

ALTER TABLE IF EXISTS public.user_captcha_log_entries
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.user_captcha_log_entries TO anon;

GRANT ALL ON TABLE public.user_captcha_log_entries TO authenticated;

GRANT ALL ON TABLE public.user_captcha_log_entries TO postgres;

GRANT ALL ON TABLE public.user_captcha_log_entries TO service_role;

COMMENT ON TABLE public.user_captcha_log_entries
    IS 'Entries of User Captcha Verifications';
CREATE POLICY "Enable SELECT access for users based on user_id"
    ON public.user_captcha_log_entries
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = user_id));
