-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable full access for users based on user_id"
    ON public.invite_links
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((wallet_id IN ( SELECT wallets.id
   FROM wallets
  WHERE (auth.uid() = wallets.user_id))));
