-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable SELECT access for users based on user_id"
    ON public.conversions
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((invite_link_id IN ( SELECT invite_links.id
   FROM invite_links
  WHERE (invite_links.wallet_id IN ( SELECT wallets.id
           FROM wallets
          WHERE (auth.uid() = wallets.user_id))))));
