service: usher-graph

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 900
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV:
      ${self:custom.nodeEnv.${opt:stage, self:provider.stage}, 'development'}
    STAGE: ${opt:stage, self:provider.stage}
    S3_REGION: ${env:S3_REGION, self:provider.region}
    S3_BUCKET: ${env:S3_BUCKET, ""}
    S3_ROOT: ${env:S3_ROOT, ""}
    CERAMIC_URL: ${env:CERAMIC_URL, ""}
    ARANGO_URL: ${env:ARANGO_URL, ""}
    ARANGO_DATABASE: ${env:ARANGO_DATABASE, ""}
    ARANGO_USERNAME: ${env:ARANGO_USERNAME, ""}
    ARANGO_PASSWORD: ${env:ARANGO_PASSWORD, ""}
    SENTRY_DSN: ${env:SENTRY_DSN, ""}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${env:S3_BUCKET, ""}/*
  stackTags:
    Project: "Usher"
  tags:
    Project: "Usher"

functions:
  ingest:
    description: "Fetch Ceramic data and ingest into Graph"
    handler: src/index.ingest
    events:
      - schedule: rate(5 minutes)
  # TODO: Commented out as this will be re-added and tested post deployment
  # backup:
  #   description: "Backup the Database on a recurring basis"
  #   handler: src/index.backup
  #   events:
  #     - schedule: rate(1 day)

custom:
  nodeEnv:
    dev: development
    prod: production
